@extends('layouts.app')

@section('content')
<x-breadcrumb title="Notes app" />
<div class="overflow-hidden rounded-xl bg-background shadow-xs" x-data="{ search: '', selected: 1, addOpen: false, newTitle: '', newColor: 'primary', notes: [{ id: 1, title: 'Meeting with design team', color: 'warning', date: '12/15/2024' }, { id: 2, title: 'Update the dashboard copy', color: 'primary', date: '12/14/2024' }, { id: 3, title: 'Review feedback from customer', color: 'error', date: '12/13/2024' }, { id: 4, title: 'Prepare product release', color: 'success', date: '12/12/2024' }, { id: 5, title: 'Plan social campaign', color: 'secondary', date: '12/11/2024' }], get filtered() { return this.notes.filter(note => note.title.toLowerCase().includes(this.search.toLowerCase())) }, get current() { return this.notes.find(note => note.id === this.selected) }, addNote() { if (!this.newTitle.trim()) return; const id = Math.max(...this.notes.map(note => note.id)) + 1; this.notes.push({ id, title: this.newTitle, color: this.newColor, date: new Date().toLocaleDateString() }); this.selected = id; this.newTitle = ''; this.addOpen = false; }, remove(id) { this.notes = this.notes.filter(note => note.id !== id); if (this.selected === id) this.selected = this.notes[0]?.id || null; } }">
    <div class="flex min-h-[530px]">
        <aside class="left-part hidden w-80 shrink-0 lg:block"><input x-model="search" type="search" placeholder="Search Notes" class="w-full rounded-md border border-defaultBorder bg-transparent p-3 text-sm outline-none focus:border-primary"><h6 class="mt-6 text-base">All Notes</h6><div class="mt-4 flex flex-col gap-3"><template x-for="note in filtered" :key="note.id"><div class="relative rounded-md p-4 transition-transform" :class="[selected === note.id ? 'scale-100' : 'scale-95', note.color === 'warning' ? 'bg-lightwarning dark:bg-darkwarning' : note.color === 'primary' ? 'bg-lightprimary dark:bg-darkprimary' : note.color === 'error' ? 'bg-lighterror dark:bg-darkerror' : note.color === 'success' ? 'bg-lightsuccess dark:bg-darksuccess' : 'bg-lightsecondary dark:bg-darksecondary']" @click="selected = note.id"><h6 class="truncate text-base" :class="note.color === 'warning' ? 'text-warning' : note.color === 'primary' ? 'text-primary' : note.color === 'error' ? 'text-error' : note.color === 'success' ? 'text-success' : 'text-secondary'" x-text="note.title"></h6><div class="flex items-center justify-between"><p class="text-xs text-ld" x-text="note.date"></p><button type="button" @click.stop="remove(note.id)" class="rounded p-1 hover:bg-white/50" aria-label="Delete note"><x-icon name="tabler:trash" size="18" /></button></div></div></template><p x-show="!filtered.length" class="rounded-md border border-error p-4 text-error">No Notes Found!</p></div></aside>
        <div class="w-full"><div class="flex items-center justify-between border-b border-ld px-6 py-4"><div class="flex items-center gap-3"><button type="button" class="btn-circle flex items-center justify-center rounded-md bg-lightprimary text-primary lg:hidden"><x-icon name="tabler:menu-2" size="18" /></button><h6 class="text-base">Edit Note</h6></div><button type="button" @click="addOpen = true" class="rounded-md bg-primary px-4 py-2 text-white">Add Note</button></div><div class="flex p-6" x-show="current"><div class="w-full"><textarea x-model="current.title" rows="5" placeholder="Edit Note" class="w-full rounded-md border border-defaultBorder bg-transparent p-6 text-sm outline-none focus:border-primary"></textarea><h6 class="mb-3 mt-4 text-base">Change Note Color</h6><div class="flex items-center gap-2"><template x-for="color in ['warning', 'primary', 'error', 'success', 'secondary']" :key="color"><button type="button" @click="current.color = color" class="flex h-7 w-7 items-center justify-center rounded-full" :class="color === 'warning' ? 'bg-warning' : color === 'primary' ? 'bg-primary' : color === 'error' ? 'bg-error' : color === 'success' ? 'bg-success' : 'bg-secondary'"><x-icon name="tabler:check" size="18" class="text-white" /></button></template></div></div></div><div x-show="!current" class="w-full py-6 text-center text-2xl text-darklink">Select a Note</div></div>
    </div>
    <div x-cloak x-show="addOpen" class="fixed inset-0 z-[70] flex items-center justify-center bg-black/40 p-4"><div @click.outside="addOpen = false" class="w-full max-w-lg rounded-xl bg-background p-6 shadow-lg dark:bg-darkgray"><h3 class="mb-5 text-xl">Add New Note</h3><textarea x-model="newTitle" rows="5" placeholder="Write your note here..." class="w-full rounded-md border border-defaultBorder bg-transparent p-4 outline-none focus:border-primary"></textarea><h6 class="pt-4 text-base">Change Note Color</h6><div class="mt-2 flex items-center gap-2"><template x-for="color in ['warning', 'primary', 'error', 'success', 'secondary']" :key="color"><button type="button" @click="newColor = color" class="flex h-7 w-7 items-center justify-center rounded-full" :class="color === 'warning' ? 'bg-warning' : color === 'primary' ? 'bg-primary' : color === 'error' ? 'bg-error' : color === 'success' ? 'bg-success' : 'bg-secondary'"><x-icon name="tabler:check" size="18" class="text-white" /></button></template></div><div class="mt-6 flex gap-2"><button type="button" @click="addNote" :disabled="!newTitle.trim()" class="rounded-md bg-primary px-4 py-2 text-white disabled:opacity-50">Save</button><button type="button" @click="addOpen = false" class="rounded-md bg-lighterror px-4 py-2 text-error">Close</button></div></div></div>
</div>
@endsection
