@extends('layouts.app')

@section('content')
    <x-breadcrumb title="Form Elements" />
    <div class="grid grid-cols-1 gap-6 xl:grid-cols-2" x-data="{ copied: false, website: 'https://matdash-nextjs-main.vercel.app/' }">
        <div class="flex flex-col gap-6">
            <section class="rounded-xl bg-background p-4 shadow-xs md:p-6"><h5 class="card-title">Default Inputs</h5><div class="mt-6 flex flex-col gap-6">
                <label class="block">Input<input type="text" required class="mt-2 w-full rounded-md border border-defaultBorder bg-transparent p-3 text-sm outline-none focus:border-primary"></label>
                <label class="block">Input with Placeholder<input type="text" placeholder="Firstname" required class="mt-2 w-full rounded-md border border-defaultBorder bg-transparent p-3 text-sm outline-none focus:border-primary"></label>
                <label class="block">Select Input<select class="mt-2 w-full rounded-md border border-defaultBorder bg-transparent p-3 text-sm outline-none focus:border-primary"><option>Select an option</option><option>United States</option><option>Canada</option><option>France</option><option>Germany</option></select></label>
                <label class="block">Password Input<input type="password" placeholder="Enter your Password" required class="mt-2 w-full rounded-md border border-defaultBorder bg-transparent p-3 text-sm outline-none focus:border-primary"></label>
                <label class="block">Date of birth<input type="date" class="mt-2 w-full rounded-md border border-defaultBorder bg-transparent p-3 text-sm outline-none focus:border-primary"></label>
                <label class="block">Time Picker Input<div class="relative mt-2"><input type="time" min="09:00" max="18:00" class="w-full rounded-md border border-defaultBorder bg-transparent p-3 pr-10 text-sm outline-none focus:border-primary"><x-icon name="solar:clock-circle-linear" size="18" class="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-gray-500" /></div></label>
                <label class="block">Card<div class="relative mt-2"><x-icon name="uim:master-card" size="20" class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" /><input type="text" placeholder="Card number" class="w-full rounded-md border border-defaultBorder bg-transparent p-3 pl-10 text-sm outline-none focus:border-primary"></div></label>
            </div></section>
            <section class="rounded-xl bg-background p-4 shadow-xs md:p-6"><h5 class="card-title">Textarea Input</h5><div class="mt-6 flex flex-col gap-6"><label>Description<textarea rows="4" placeholder="Leave a comment..." class="mt-2 w-full rounded-md border border-defaultBorder bg-transparent p-4 text-sm outline-none focus:border-primary"></textarea></label><label>Description<textarea rows="4" disabled placeholder="Disabled" class="mt-2 w-full rounded-md border border-defaultBorder bg-transparent p-4 text-sm opacity-60"></textarea></label><label class="text-red-600">Description<textarea rows="4" placeholder="Leave a comment..." class="mt-2 w-full rounded-md border border-red-600 bg-transparent p-4 text-sm text-red-600 outline-none"></textarea></label></div></section>
            <section class="rounded-xl bg-background p-4 shadow-xs md:p-6"><h5 class="card-title">Input Colors</h5><div class="mt-6 flex flex-col gap-6"><label class="text-warning">Warning<input placeholder="Warning input" class="mt-2 w-full rounded-md border border-warning bg-transparent p-3 text-sm outline-none"></label><label class="text-info">Info<input placeholder="Info input" class="mt-2 w-full rounded-md border border-info bg-transparent p-3 text-sm outline-none"></label><label class="text-success">Success<input placeholder="Success input" class="mt-2 w-full rounded-md border border-success bg-transparent p-3 text-sm outline-none"></label></div></section>
        </div>
        <div class="flex flex-col gap-6">
            <section class="rounded-xl bg-background p-4 shadow-xs md:p-6"><h5 class="card-title">Input Group</h5><div class="mt-6 flex flex-col gap-6">
                @foreach ([['solar:letter-linear', 'email', 'name@example.com'], ['solar:phone-rounded-linear', 'tel', '+1'], ['solar:global-linear', 'text', 'www.example.com'], ['solar:link-round-angle-linear', 'text', 'https://matdash-nextjs-main.vercel.app/']] as [$icon, $type, $placeholder])
                    <div class="relative"><x-icon name="{{ $icon }}" size="18" class="absolute left-3 top-1/2 -translate-y-1/2" /><input type="{{ $type }}" placeholder="{{ $placeholder }}" class="w-full rounded-md border border-defaultBorder bg-transparent p-3 pl-10 text-sm outline-none focus:border-primary"></div>
                @endforeach
                <label>Website<div class="mt-2 flex gap-2"><input x-model="website" class="min-w-0 flex-1 rounded-md border border-defaultBorder bg-transparent p-3 text-sm outline-none focus:border-primary"><button type="button" @click="navigator.clipboard.writeText(website); copied = true; setTimeout(() => copied = false, 1500)" class="rounded-full border border-ld bg-primary/10 px-3 py-2 text-sm text-primary" x-text="copied ? 'Copied' : 'Copy'"></button></div></label>
            </div></section>
            <section class="rounded-xl bg-background p-4 shadow-xs md:p-6"><h5 class="card-title">File Input</h5><input type="file" class="mt-6 w-full rounded-md border border-defaultBorder bg-transparent p-3 text-sm"></section>
            <section class="rounded-xl bg-background p-4 shadow-xs md:p-6"><h5 class="card-title">Checkbox</h5><div class="mt-6 flex flex-wrap gap-6"><label class="flex items-center gap-2"><input type="checkbox" class="accent-primary">Default</label><label class="flex items-center gap-2"><input type="checkbox" checked class="accent-primary">Checked</label><label class="flex items-center gap-2 opacity-60"><input type="checkbox" disabled>Disabled</label></div></section>
            <section class="rounded-xl bg-background p-4 shadow-xs md:p-6"><h5 class="card-title">Radio Buttons</h5><div class="mt-6 flex flex-wrap gap-6"><label class="flex items-center gap-2"><input type="radio" name="example-radio" checked class="accent-primary">Default</label><label class="flex items-center gap-2"><input type="radio" name="example-radio" class="accent-primary">Selected</label><label class="flex items-center gap-2 opacity-60"><input type="radio" disabled>Disabled</label></div></section>
            <section class="rounded-xl bg-background p-4 shadow-xs md:p-6"><h5 class="card-title">Toggle Switch</h5><div class="mt-6 grid grid-cols-2 gap-6 sm:grid-cols-3"><label class="flex items-center gap-2"><input type="checkbox" class="h-5 w-9 accent-primary">Toggle me</label><label class="flex items-center gap-2"><input type="checkbox" checked class="h-5 w-9 accent-primary">Toggle me (checked)</label><label class="flex items-center gap-2 opacity-60"><input type="checkbox" disabled class="h-5 w-9">Disabled</label><label class="flex items-center gap-2 opacity-60"><input type="checkbox" checked disabled class="h-5 w-9">Disabled (checked)</label></div></section>
        </div>
    </div>
@endsection
