@extends('layouts.app')

@section('content')
    <x-breadcrumb title="Table" />
    <div class="relative w-full rounded-xl bg-background p-6 shadow-xs"><h5 class="card-title">Table</h5><div class="mt-3 overflow-x-auto"><table class="w-full text-left"><thead class="border-y border-defaultBorder text-sm text-darklink"><tr><th class="p-6 font-medium">Products</th><th class="p-4 font-medium">Payment</th><th class="p-4 font-medium">Status</th><th class="p-4"></th></tr></thead><tbody>
        @foreach ([['dash-prd-1.jpg', 'iPhone 13 pro max-Pacific Blue-128GB storage', '$180', 'Partially paid', 45, 'bg-warning', 'Confirmed', 'bg-lightsuccess text-success'], ['dash-prd-2.jpg', 'Apple MacBook Pro 13 inch-M1-8/256GB-space', '$120', 'Full paid', 100, 'bg-success', 'Confirmed', 'bg-lightsuccess text-success'], ['dash-prd-3.jpg', 'PlayStation 5 DualSense Wireless Controller', '$120', 'Cancelled', 100, 'bg-error', 'Cancelled', 'bg-lighterror text-error'], ['s5.jpg', 'Amazon Basics Mesh, Mid-Back, Swivel Office', '$120', 'Partially paid', 45, 'bg-warning', 'Confirmed', 'bg-lightsuccess text-success'], ['dash-prd-4.jpg', 'Sony X85J 75 Inch Sony 4K Ultra HD LED Smart', '$120', 'Full paid', 100, 'bg-success', 'Confirmed', 'bg-lightsuccess text-success']] as [$image, $name, $payment, $paymentStatus, $progress, $color, $status, $badge])
            <tr class="border-b border-defaultBorder"><td class="whitespace-nowrap p-6"><div class="flex items-center gap-3"><img src="{{ asset('images/products/' . $image) }}" alt="{{ $name }}" class="h-[60px] w-[60px] rounded-md"><h6 class="line-clamp-2 max-w-56 text-sm">{{ $name }}</h6></div></td><td class="p-4"><h5 class="text-base">{{ $payment }}<span class="opacity-70"> <span class="mx-1">/</span>499</span></h5><p class="mb-2 text-sm font-medium opacity-70">{{ $paymentStatus }}</p><div class="h-2 w-32 overflow-hidden rounded-full bg-lightgray"><div class="{{ $color }} h-full" style="width: {{ $progress }}%"></div></div></td><td class="p-4"><span class="rounded-md px-2 py-1 text-xs {{ $badge }}">{{ $status }}</span></td><td class="p-4 text-right" x-data="{ open: false }"><button type="button" @click="open = !open" class="inline-flex h-9 w-9 items-center justify-center rounded-full hover:bg-lightprimary hover:text-primary"><x-icon name="solar:menu-dots-bold" size="22" /></button><div x-cloak x-show="open" @click.outside="open = false" class="absolute z-20 mt-1 w-28 rounded-md bg-background p-1 text-left shadow-md dark:bg-darkgray"><a href="#" class="block px-3 py-2 hover:bg-lightprimary">Add</a><a href="#" class="block px-3 py-2 hover:bg-lightprimary">Edit</a><a href="#" class="block px-3 py-2 hover:bg-lightprimary">Delete</a></div></td></tr>
        @endforeach
    </tbody></table></div></div>
@endsection
