@extends('layouts.app')

@section('content')
<x-breadcrumb title="Tickets App" />
<div class="rounded-xl bg-background p-6 shadow-xs" x-data="{ title: '', description: '', date: new Date().toISOString().slice(0, 10), agent: { name: 'Liam', photo: 'user-10.jpg' }, open: false, agents: [{ name: 'Liam', photo: 'user-10.jpg' }, { name: 'Steve', photo: 'user-2.jpg' }, { name: 'Jack', photo: 'user-3.jpg' }, { name: 'John', photo: 'user-8.jpg' }], save() { if (!this.title || !this.description) { alert('Please fill out all fields.'); return; } window.location.href = '{{ route('apps.tickets') }}'; } }">
    <h2 class="mb-4 text-lg font-semibold">Create New Ticket</h2><p>ID : 9</p><p>Date : <span x-text="new Date(date + 'T00:00:00').toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })"></span></p>
    <div class="my-6 rounded-md bg-lightgray p-6 dark:bg-gray-800/70"><div class="grid grid-cols-1 gap-6 md:grid-cols-2"><label>Ticket Title<input x-model="title" placeholder="Ticket Title" class="mt-2 w-full rounded-md border border-defaultBorder bg-transparent p-3 outline-none focus:border-primary"></label><label>Ticket Description<input x-model="description" placeholder="Ticket Description" class="mt-2 w-full rounded-md border border-defaultBorder bg-transparent p-3 outline-none focus:border-primary"></label></div><label class="mt-6 block">Ticket Date<input x-model="date" type="date" class="mt-2 rounded-md border border-defaultBorder bg-transparent p-3 outline-none focus:border-primary"></label><div class="mt-6 flex flex-wrap items-center justify-between gap-3"><div class="relative" @click.outside="open = false"><button type="button" @click="open = !open" class="flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-white"><img :src="'{{ asset('images/profile') }}/' + agent.photo" class="h-6 w-6 rounded-full"><span x-text="agent.name"></span><x-icon name="solar:alt-arrow-down-linear" size="16" /></button><div x-cloak x-show="open" class="absolute z-20 mt-1 w-40 rounded-md bg-background p-1 shadow-md dark:bg-darkgray"><template x-for="person in agents" :key="person.name"><button type="button" @click="agent = person; open = false" class="flex w-full items-center gap-2 rounded px-3 py-2 text-left hover:bg-lightprimary"><img :src="'{{ asset('images/profile') }}/' + person.photo" class="h-6 w-6 rounded-full"><span x-text="person.name"></span></button></template></div></div><div class="flex gap-3"><button type="button" @click="save" class="rounded-md bg-primary px-4 py-2 text-white">Save</button><a href="{{ route('apps.tickets') }}" class="rounded-md bg-lighterror px-4 py-2 text-error">Cancel</a></div></div></div>
</div>
@endsection
