@extends('layouts.app')

@section('content')
<x-breadcrumb title="Tickets App" />
<div class="rounded-xl bg-background p-6 shadow-xs" x-data="{ filter: 'total_tickets', search: '', tickets: [{ id: 1, title: 'Sed ut perspiciatis unde omnis iste', description: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', status: 'Closed', image: 'user-10.jpg', agent: 'Liam', date: 'Fri, Dec 1' }, { id: 2, title: 'Consequuntur magni dolores eos qui ratione', description: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', status: 'Pending', image: 'user-2.jpg', agent: 'Steve', date: 'Sat, Dec 2' }, { id: 3, title: 'Exercitationem ullam corporis', description: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', status: 'Open', image: 'user-3.jpg', agent: 'Jack', date: 'Sun, Dec 3' }, { id: 4, title: 'Sed ut perspiciatis unde omnis iste', description: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', status: 'Closed', image: 'user-4.jpg', agent: 'Steve', date: 'Mon, Dec 4' }, { id: 5, title: 'Exercitationem ullam corporis', description: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', status: 'Closed', image: 'user-5.jpg', agent: 'Liam', date: 'Tue, Dec 5' }, { id: 6, title: 'Consequuntur magni dolores eos qui ratione', description: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', status: 'Pending', image: 'user-6.jpg', agent: 'Jack', date: 'Wed, Dec 6' }, { id: 7, title: 'Sed ut perspiciatis unde omnis iste', description: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', status: 'Open', image: 'user-7.jpg', agent: 'Steve', date: 'Thu, Dec 7' }, { id: 8, title: 'Consequuntur magni dolores eos qui ratione', description: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', status: 'Closed', image: 'user-8.jpg', agent: 'John', date: 'Fri, Dec 8' }], get visible() { return this.tickets.filter(ticket => (this.filter === 'total_tickets' || ticket.status === this.filter) && ticket.title.toLowerCase().includes(this.search.toLowerCase())) }, count(status) { return status === 'total_tickets' ? this.tickets.length : this.tickets.filter(ticket => ticket.status === status).length; } }">
    <div class="grid grid-cols-12 gap-6">
        @foreach ([['total_tickets', 'bg-lightprimary', 'text-primary', 'Total Tickets'], ['Pending', 'bg-lightwarning', 'text-warning', 'Pending Tickets'], ['Open', 'bg-lightsuccess', 'text-success', 'Open Tickets'], ['Closed', 'bg-lighterror', 'text-error', 'Closed Tickets']] as [$value, $background, $color, $label])
            <button type="button" @click="filter = '{{ $value }}'" class="col-span-12 rounded-md p-[30px] text-center md:col-span-6 lg:col-span-3 {{ $background }}"><h3 class="{{ $color }} text-2xl" x-text="count('{{ $value }}')"></h3><h6 class="{{ $color }} text-base">{{ $label }}</h6></button>
        @endforeach
    </div>
    <div class="my-6"><div class="mb-4 flex items-center justify-between gap-4"><a href="{{ route('apps.tickets.create') }}" class="rounded-md bg-primary px-4 py-2 text-white">Create Ticket</a><div class="relative w-full max-w-60"><x-icon name="tabler:search" size="18" class="absolute left-2 top-1/2 -translate-y-1/2 text-gray-400" /><input x-model="search" placeholder="Search" class="w-full rounded-md border border-defaultBorder bg-transparent p-2 pl-8 text-sm outline-none focus:border-primary"></div></div><div class="overflow-x-auto"><table class="w-full text-left"><thead class="border-y border-defaultBorder text-sm text-darklink"><tr><th class="p-4 font-medium">Id</th><th class="p-4 font-medium">Ticket</th><th class="p-4 font-medium">Assigned To</th><th class="p-4 font-medium">Status</th><th class="p-4 font-medium">Date</th><th class="p-4 text-end font-medium">Action</th></tr></thead><tbody><template x-for="ticket in visible" :key="ticket.id"><tr class="border-b border-defaultBorder"><td class="p-4" x-text="ticket.id"></td><td class="max-w-md p-4"><h6 class="truncate text-base" x-text="ticket.title"></h6><p class="truncate text-sm text-muted-foreground" x-text="ticket.description"></p></td><td class="p-4"><div class="flex items-center gap-3"><img :src="'{{ asset('images/profile') }}/' + ticket.image" :alt="ticket.agent" class="h-10 w-10 rounded-full"><h6 class="text-base" x-text="ticket.agent"></h6></div></td><td class="p-4"><span class="rounded-md px-2 py-1 text-xs" :class="ticket.status === 'Open' ? 'bg-lightsuccess text-success' : ticket.status === 'Closed' ? 'bg-lighterror text-error' : 'bg-lightwarning text-warning'" x-text="ticket.status"></span></td><td class="p-4"><p class="text-sm text-muted-foreground" x-text="ticket.date"></p></td><td class="p-4 text-end"><button type="button" @click="tickets = tickets.filter(item => item.id !== ticket.id)" class="rounded p-2 hover:text-red-600" title="Delete Ticket"><x-icon name="tabler:trash" size="18" /></button></td></tr></template></tbody></table></div></div>
</div>
@endsection
