@extends('layouts.app')

@section('content')
<x-breadcrumb title="User Profile" />
<div class="flex flex-col gap-6" x-data="{ modal: null, personal: { firstName: 'Mathew', lastName: 'Anderson', email: 'mathew.anderson@gmail.com', phone: '(347) 528-1947', position: 'Team Leader' }, address: { location: 'United States', state: 'San Diego, California, United States', pin: '92101', zip: '30303', taxNo: 'GA45273910' } }">
    <section class="relative w-full overflow-hidden rounded-xl bg-background p-6 shadow-xs"><div class="flex flex-col items-center gap-6 sm:flex-row"><img src="{{ asset('images/profile/user-1.jpg') }}" alt="Mathew Anderson" width="80" height="80" class="rounded-full"><div class="flex w-full flex-wrap items-center justify-center gap-4 sm:justify-between"><div class="flex flex-col gap-1.5 text-center sm:text-left"><h5 class="card-title"><span x-text="personal.firstName"></span> <span x-text="personal.lastName"></span></h5><div class="flex flex-wrap items-center gap-1 md:gap-3"><p class="text-sm text-gray-500" x-text="personal.position"></p><span class="hidden h-4 w-px bg-gray-300 xl:block"></span><p class="text-sm text-gray-500" x-text="address.location"></p></div></div><div class="flex items-center gap-2">@foreach (['streamline-logos:facebook-logo-2-solid', 'streamline-logos:x-twitter-logo-solid', 'ion:logo-github', 'streamline-flex:dribble-logo-remix'] as $icon)<a href="#" class="flex h-11 w-11 items-center justify-center rounded-full shadow-md hover:bg-gray-50 dark:hover:bg-white/[0.03]"><x-icon name="{{ $icon }}" size="20" /></a>@endforeach</div></div></div></section>
    <div class="grid grid-cols-1 gap-6 xl:grid-cols-2">
        <section class="relative w-full space-y-6 rounded-xl bg-background p-4 shadow-xs md:p-6"><h5 class="card-title">Personal Information</h5><div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:gap-7 2xl:gap-x-32"><template x-for="[label, key] in [['First Name', 'firstName'], ['Last Name', 'lastName'], ['Email', 'email'], ['Phone', 'phone'], ['Position', 'position']]" :key="key"><div><p class="text-xs text-gray-500" x-text="label"></p><p x-text="personal[key]"></p></div></template></div><div class="flex justify-end"><button type="button" @click="modal = 'personal'" class="flex items-center gap-1.5 rounded-md bg-primary px-4 py-2 text-white"><x-icon name="ic:outline-edit" size="18" />Edit</button></div></section>
        <section class="relative w-full space-y-6 rounded-xl bg-background p-4 shadow-xs md:p-6"><h5 class="card-title">Address Details</h5><div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:gap-7 2xl:gap-x-32"><template x-for="[label, key] in [['Location', 'location'], ['Province / State', 'state'], ['PIN Code', 'pin'], ['ZIP', 'zip'], ['Federal Tax No.', 'taxNo']]" :key="key"><div><p class="text-xs text-gray-500" x-text="label"></p><p x-text="address[key]"></p></div></template></div><div class="flex justify-end"><button type="button" @click="modal = 'address'" class="flex items-center gap-1.5 rounded-md bg-primary px-4 py-2 text-white"><x-icon name="ic:outline-edit" size="18" />Edit</button></div></section>
    </div>
    <div x-cloak x-show="modal" class="fixed inset-0 z-[70] flex items-center justify-center bg-black/40 p-4" @keydown.escape.window="modal = null"><div @click.outside="modal = null" class="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-background p-6 shadow-lg dark:bg-darkgray"><div class="mb-6 flex items-center justify-between"><h3 class="text-xl" x-text="modal === 'personal' ? 'Edit Personal Information' : 'Edit Address Details'"></h3><button type="button" @click="modal = null"><x-icon name="solar:close-circle-linear" size="22" /></button></div><div class="grid grid-cols-1 gap-4 lg:grid-cols-2" x-show="modal === 'personal'"><template x-for="[label, key] in [['First Name', 'firstName'], ['Last Name', 'lastName'], ['Email', 'email'], ['Phone', 'phone'], ['Position', 'position']]" :key="key"><label class="flex flex-col gap-2"><span x-text="label"></span><input x-model="personal[key]" class="rounded-md border border-defaultBorder bg-transparent p-3 outline-none focus:border-primary"></label></template></div><div class="grid grid-cols-1 gap-4 lg:grid-cols-2" x-show="modal === 'address'"><template x-for="[label, key] in [['Location', 'location'], ['Province / State', 'state'], ['PIN Code', 'pin'], ['ZIP', 'zip'], ['Federal Tax No.', 'taxNo']]" :key="key"><label class="flex flex-col gap-2"><span x-text="label"></span><input x-model="address[key]" class="rounded-md border border-defaultBorder bg-transparent p-3 outline-none focus:border-primary"></label></template></div><div class="mt-6 flex gap-2"><button type="button" @click="modal = null" class="rounded-md bg-primary px-4 py-2 text-white">Save Changes</button><button type="button" @click="modal = null" class="rounded-md bg-lighterror px-4 py-2 text-error">Close</button></div></div></div>
</div>
@endsection
